service: budget-assistant-server-aws

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: basrv.dillontarr.com
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'